In [1]:
import numpy as np

###  ndarray important attributes
---


In [2]:
a = np.arange(15).reshape(3,5)

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
a.itemsize

4

In [10]:
a.size

15

In [11]:
type(a)

numpy.ndarray

### Array Creation  
---

 you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.
***

In [6]:
a = np.array([1,2,3,4],dtype=float)

In [7]:
a.dtype

dtype('float64')

NumPy offers several functions to create arrays with initial placeholder content.    
The function `zeros` creates an array full of zeros, the function `ones` creates an array full of ones, and the function `empty` creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is `float64`.
***

In [10]:
np.zeros((3,4),dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [12]:
np.empty((2,4))

array([[0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 6.7192928e-321, 8.4560344e-307, 1.2461147e-306]])

To create sequences of numbers, NumPy provides a function analogous to `range` that returns arrays instead of lists.

In [13]:
np.arange(10,30,5)

array([10, 15, 20, 25])

When `arange` is used with floating point arguments, it is generally not possible to predict the **number** of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function `linspace` that receives as an argument the number of elements that we want, instead of the step:

In [14]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

### Basic Operations
---

Arithmetic operators on arrays apply *elementwise*. A new array is created and filled with the result.
***

In [15]:
a = np.array([20,30,40])
b = np.arange(3)

In [16]:
a-b

array([20, 29, 38])

Unlike in many matrix languages, the product operator `*` operates elementwise in NumPy arrays. The matrix product can be performed using the `@` operator (in python >=3.5) or the dot function or method:
***

In [17]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

In [18]:
A*B

array([[2, 0],
       [0, 4]])

In [19]:
A@B

array([[5, 4],
       [3, 4]])

In [20]:
A.dot(B)

array([[5, 4],
       [3, 4]])

Some operations , such as `+=` and `*=` ,act in place to modify an existing array rather than create a new one.

In [21]:
a = np.ones((3,4))

In [22]:
a += 3

In [23]:
a

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [24]:
a = np.ones(3,dtype=np.int16)
b = np.linspace(0,3.14,3)

In [25]:
b.dtype.name

'float64'

In [26]:
c = a + b
c.dtype.name

'float64'

Many unary operations,such as computing the sum of all the elements in the arrays, are implemented as methods of the `ndarray` class.

In [28]:
c.sum()

7.710000000000001

In [29]:
c.max()

4.140000000000001

In [31]:
c.min()

1.0

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the `axis` parameter you can apply an operation along the specified axis of an array:

In [32]:
b = np.arange(12).reshape(3,4)

In [33]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [37]:
b.cumsum(axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

### Universal Functions
***

NumPy provides familiar mathematical functions such as cos and exp. In NumPy, these are called "universal functions"(ufunc).Within NumPy, these functions operate elementwise on an array , producing an array as output.

In [38]:
B = np.arange(3)

In [39]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

### Indexing,Slicing and Iterating
***

**One-dimensional** arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.   
**Multidimensional** arrays can have one index per axis. These indices are given in a tuple separated by commas:  
When fewer indices are provided than the number of axes, the missing indices are considered complete slices  
The dots (`...`) represent as many colons as needed to produce a complete indexing tuple. For example, if `x` is an array with 5 axes, then
* `x[1,2,...]` is quivalent to `x[1,2,:,:,:]`,  
* `x[...,3]` to `x[:,:,:,:,3]` and  
* `x[4,...,5,:]` to `x[4,:,:,5,:]`
***

In [40]:
b = np.arange(12).reshape(3,4)

In [43]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
b[...,-1]

array([ 3,  7, 11])

**Iterating** over multidimensional array is done with respect to the first axis:  
However, if one wants to perform an operation on each element in the array, one can use the `flat` attribute which is an iterator over all the elements of the array:

In [46]:
for row in b:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [47]:
for element in b.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11


### Shape Manipulation
***
Changing the shape of an array
***
The shape of an array can be changed with various commands. Note that the following three commands all return a modified array. but do not change the original array:

In [48]:
a = np.floor(10*np.random.random((3,4)))

In [50]:
a.ravel()

array([3., 2., 7., 5., 1., 7., 3., 7., 1., 7., 0., 4.])

In [52]:
a.shape

(3, 4)

The `reshape` function returns its argument with a modified shape, whereas the `ndarray.resize` method modifies the array itself:

In [53]:
a

array([[3., 2., 7., 5.],
       [1., 7., 3., 7.],
       [1., 7., 0., 4.]])

In [54]:
a.resize((2,6))

In [55]:
a

array([[3., 2., 7., 5., 1., 7.],
       [3., 7., 1., 7., 0., 4.]])

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculcated:

In [56]:
a.reshape(3,-1)

array([[3., 2., 7., 5.],
       [1., 7., 3., 7.],
       [1., 7., 0., 4.]])

Stacking together different arrays
***

In [58]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

In [59]:
a


array([[3., 6.],
       [3., 3.]])

In [60]:
b

array([[1., 7.],
       [5., 4.]])

In [63]:
np.vstack((a,b))

array([[3., 6.],
       [3., 3.],
       [1., 7.],
       [5., 4.]])

In [64]:
np.hstack((a,b))

array([[3., 6., 1., 7.],
       [3., 3., 5., 4.]])

In [65]:
np.column_stack((a,b))

array([[3., 6., 1., 7.],
       [3., 3., 5., 4.]])

In [66]:
a = np.array([1,2])
b = np.array([3,4])

In [67]:
np.column_stack((a,b))

array([[1, 3],
       [2, 4]])

`r_c` and `c_` are useful for creating arrays by stacking numbers along one axis, They allow the use of range literals(":")

In [68]:
np.c_[a,b]

array([[1, 3],
       [2, 4]])

### Copies and Views
***
When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not:

#### No copy at All
***
Simple assignments make no copy of array objects or of their data.

In [69]:
a = np.arange(12)
b = a 

In [70]:
b is a

True

In [72]:
b.resize(3,4)

In [73]:
a.shape

(3, 4)

Python passes mutable objects as references, so function calls make no copy.


In [74]:
def f(x):
    print(id(x))

id(a) # id is a unique identifier of an object

2302873363520

In [75]:
f(a)

2302873363520


#### View or Shallow Copy
***
Different array objects can share the same data. The `view` method creates a new array object that looks at the same data.  

In [20]:
a = np.arange(12).reshape(3,4)

In [21]:
c = a.view()

In [23]:
c.flags.owndata

False

Slicing an array returns a view of it:

In [4]:
s = a[:,1:3]

In [5]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
s.base is a

False

In [6]:
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [7]:
s[0,0] = 100

In [8]:
a

array([[  0, 100,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

#### Deep Copy
***
The `copy` method makes a complete copy of the array and its data.

In [9]:
d = a.copy()

In [10]:
d is a 

False

In [11]:
d.base is a

False

In [24]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
d[0,0] =100

In [26]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Sometimes `copy` should be called after slicing if the original array is not required anymore. For example, suppose `a` is a huge intermediate result and the final result `b` only contains a small fraction of `a`, a deep copy should be made when constructing `b` with slicing:

In [27]:
a = np.arange(int(1e8))

In [28]:
b = a[:100].copy()

In [29]:
del a

If `b = a[:100]` is used instead, `a` is referenced by `b` and will persist in memory even if `del a` is executed.

### Tricks and Tips
***
#### "Automatic" Reshaping
***
To change the dimensions of an array, you can omit one of the sizes which will then be deduced automatically:

In [30]:
a = np.arange(30)

In [31]:
a.shape = 2,-1,3 # -1 means "whatever is needed"

In [32]:
a.shape

(2, 5, 3)